# Generated by Django 4.2.6 on 2023-11-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.ramo'),
        ),
    ]
