# Generated by Django 4.2.6 on 2023-11-24 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_seccion_ramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionalumno',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.seccion'),
        ),
    ]
