# Generated by Django 4.2.6 on 2023-12-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_asistencia_fecha_hora_alter_asistencia_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado')], default='Lunes', max_length=30)),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_termino', models.TimeField(verbose_name='Hora de termino')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.seccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
