# Generated by Django 4.2.6 on 2023-12-06 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_clase_delete_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.clase')),
            ],
        ),
    ]
